### ISSUE TITLE
add start option

### ISSUE THREAD

**Issue by onto2000** [adoroszlai/leaflet-distance-markers#12]
please add a start option

add line 33: var start = options.start !== undefined ? options.start : 1;
replace line 64 with: var icon = L.divIcon({ className: cssClass, html: i+start, iconSize: iconSize });
replace line 54 with: var marker = L.marker(position.latLng, { title: i+start, icon: icon });

good to use if you want to display the kilometers for rivers

the rhine in germany starts at basel km 165

**Comment by onto2000** [comment]
sorry 

add line 33: var start = options.start !== undefined ? options.start : 0;

**Comment by adoroszlai** [comment]
Thanks @onto2000 for the idea, sounds good to me.  Would you like to open a pull request with this change?

**Comment by onto2000** [comment]
yes

**Comment by adoroszlai** [comment]
Thanks to @matzepan this is now possible with the following options:

```
distanceMarkers: {
	textFunction: function(distance, i, offset) {
		return i + start;
	}
}
```
