### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by PhilWhitehurst** [adoroszlai/leaflet-distance-markers#2]
Because of the way it interpolates the markers along the full track it can be extremely slow for long tracks. Think GPX tracks 200km and above with thousands of trackpoints. This means the map hangs with a grey screen whilst your code calculates the marker positions. I think it can be made significantly faster calling the cumulative distance function of geometry utils , then working once through the array to find points either side of the marker position then call the interpolation function with a line of 2 points. 

I'm going to make the above change in a fork and see how I get on.

**Comment by adoroszlai** [comment]
Thank you, looking forward to the enhancement.

I use [GpsPrune](http://activityworkshop.net/software/gpsprune/) to reduce the number of trackpoints.

**Comment by PhilWhitehurst** [comment]
I've created a pull request for my performance enhancements

**Comment by adoroszlai** [comment]
Thanks a lot!  I've merged it.  I've also tweaked whitespace and formatting a bit in 2cf0671
