### ISSUE TITLE
GeoJSON MultiLineStrings cause error

### ISSUE THREAD

**Issue by ghost** [adoroszlai/leaflet-distance-markers#6]
I'm using this plugin with Leaflet's GeoJSON function and overriding the default options like this:

```
L.geoJson(geojson, {
      distanceMarkers: { showAll: 11, cssClass: 'location-marker', offset: someOffset }
 }).addTo(map);
```

which works fine, as long as the GeoJSON data is a LineString (which 99% of my records are). However, a few of my GeoJSON records are MultiLineString and they product the following error:

```
Uncaught TypeError: coords[i].distanceTo is not a function
```

Is there a way I can selectively turn off distance markers if the GeoJSON is a MultiLineString?

**Comment by adoroszlai** [comment]
Hi @matbeard,

I do not immediately see the problem.  I tried a GeoJSON MultiLineString (see a687a64e146a49ac041a770880487c5feb1c7c37, branch geojson); markers are shown for both line segments.  Could you please give me more context by showing how you create the `geojson` variable?

**Comment by ghost** [comment]
The geojson is coming from a database. All the LineStrings work fine, so maybe there's something wrong with the implementation of MultiLineString in my source data, but I don't think so?

Here's an example of a geojson string that causes the issue (sorry it's quite long):

{"type":"MultiLineString","coordinates":[[[-1.3721944914854,53.430374682636],[-1.3717131656866,53.43121929879],[-1.3714288231093,53.43171824743],[-1.3711433781899,53.432126197315],[-1.3701982119901,53.433265027295],[-1.3696293670381,53.433901643305],[-1.3691384034203,53.43441195457],[-1.3690385454589,53.434509682443],[-1.3686657552547,53.434863772466],[-1.3681365482013,53.435319424232],[-1.3677415692327,53.435646230303],[-1.3675462127576,53.435804709361],[-1.3672486242701,53.436033648281],[-1.3667438157178,53.43639830499],[-1.3662092828106,53.436744815618],[-1.3652170328613,53.43730173596],[-1.3639461011959,53.43794655739],[-1.3629635096906,53.43842449114],[-1.3405742027166,53.448308741753],[-1.3386501535795,53.44919072915],[-1.3340430545877,53.451245580989],[-1.3313607214776,53.452548746746],[-1.3290708925568,53.453779019016],[-1.3284896111445,53.454106725921],[-1.3272106834709,53.454895838711],[-1.3249648514506,53.456366555731],[-1.3243261918216,53.45679247892],[-1.3238925671605,53.457089268137],[-1.3233767766743,53.457454650497],[-1.3222899240611,53.458249921324],[-1.321796599922,53.458611927656],[-1.3186788931419,53.460920181537],[-1.3129884005715,53.465244283231],[-1.3117126265909,53.466291555067],[-1.311352644645,53.466607787691],[-1.3104972531522,53.467415241543],[-1.3101743510892,53.467743810154],[-1.3094009553348,53.468541913659],[-1.3087626353276,53.469288641157],[-1.3081391295372,53.470122604811],[-1.3076663647424,53.470817125587],[-1.3069757482785,53.471998644605],[-1.3065824757138,53.472782834006],[-1.3063322105367,53.473343369704],[-1.306102438147,53.473935663792],[-1.3058765193432,53.474623825589],[-1.3055742470494,53.475784857922],[-1.3053586459449,53.477059038467],[-1.30530899586,53.477744897159],[-1.3053157545612,53.47837097657],[-1.3054403544815,53.481279890137],[-1.3054434339491,53.481348778876],[-1.3054691577905,53.481946788732]],[[-1.4304570035502,53.580391413526],[-1.4305666142081,53.580562211536],[-1.4309086903791,53.581211291765],[-1.4309168772526,53.58122813902],[-1.4312520930603,53.581884987497],[-1.4328412433145,53.584998741902],[-1.4329494394177,53.585159445857],[-1.434469699749,53.588089217029],[-1.435017448884,53.589361990167],[-1.4354669775052,53.590541285386],[-1.4357717366972,53.59141987276],[-1.4359216106987,53.591947298982],[-1.4360855717991,53.592689092595],[-1.4362444287575,53.593691156683],[-1.4363713034878,53.595304549956],[-1.4363760855379,53.596363656296],[-1.4362394538991,53.598740980342],[-1.4362758165645,53.599471736365],[-1.4363268716777,53.599953538335],[-1.4364275211357,53.600513808575],[-1.4365758209912,53.601127334367],[-1.4367476342561,53.601677548518],[-1.4369287396376,53.602157732664],[-1.4372586532137,53.602872403705],[-1.4377086090604,53.603656883997],[-1.4377900597985,53.603785845208],[-1.4381370256777,53.604298229375],[-1.4385158869168,53.604802681506],[-1.439273800513,53.605683894064],[-1.439779556513,53.606197915603],[-1.4402396434762,53.606624561211],[-1.4413839158661,53.607556003913],[-1.4422576919859,53.608225180521],[-1.4428706924581,53.608720471016],[-1.4448338253747,53.610438016603],[-1.4453138258912,53.610896858928],[-1.4462616334096,53.611842012591],[-1.4470556665093,53.612715521377],[-1.4480699595728,53.613966598333],[-1.4487258279732,53.614891483254],[-1.449059518114,53.615395665722],[-1.4558278416582,53.624520247695],[-1.4586797881072,53.628505035881],[-1.4634566691076,53.634937973837],[-1.4667283212888,53.639330630469],[-1.4674046462378,53.640270194435],[-1.4679238029036,53.641071292555],[-1.4682167877204,53.641581196946],[-1.4685388181018,53.642186460526],[-1.4689392439957,53.643051742836],[-1.4693360264553,53.644088144771],[-1.4695382261851,53.644728405173],[-1.4697465386824,53.645718921289],[-1.4698509589839,53.646616963911],[-1.4698728012277,53.647167405017],[-1.4698612466287,53.64790689291],[-1.4698423419267,53.648330014139],[-1.4697780021367,53.648877754683],[-1.4696744104868,53.649481516194],[-1.4695101548931,53.650159602773],[-1.4691981437429,53.651157044593],[-1.4688631489894,53.652114906997],[-1.4685842890301,53.652817318531],[-1.4679104201976,53.654315596181],[-1.4663366268577,53.657519480917],[-1.4659659618877,53.658133122092],[-1.4657072451376,53.658500290379],[-1.4649997657824,53.659419043164],[-1.4647445869297,53.659725410421],[-1.4643866910508,53.660136462856],[-1.464337889903,53.660192520292]],[[-1.4323676069059,53.69328466819],[-1.4313661689391,53.693970937099],[-1.4303573760912,53.694653252785],[-1.429362765553,53.695325938171],[-1.4283320061009,53.696100063938],[-1.4275647912365,53.696710856169],[-1.425915809297,53.69807697437],[-1.4249359475541,53.698848815899],[-1.4245326017338,53.69925315735],[-1.4221760261475,53.701953696579],[-1.4211280391151,53.703109713048],[-1.4195085892177,53.704823873679],[-1.41882584006,53.70560759279],[-1.4180251396812,53.706510350712],[-1.4178830175579,53.706657031615],[-1.4158013158152,53.708867302231],[-1.4155560712828,53.7091263429],[-1.4151638129248,53.709541258774],[-1.4069128265016,53.718231448502],[-1.4048966342081,53.720429960657],[-1.4044960357567,53.720886100754],[-1.404012279825,53.721533940231],[-1.4032238153356,53.722778840397],[-1.4028625312853,53.723498444406],[-1.4024803508253,53.724579529902],[-1.4022595100381,53.725398037028],[-1.4021553305933,53.725998631082],[-1.4021113264822,53.726383835051],[-1.4020896167249,53.727220052632],[-1.4020991808137,53.727401725047],[-1.4021624371034,53.728179331664],[-1.4023322473554,53.729246898563],[-1.4024314619811,53.729736998589],[-1.4025608936141,53.730178568958],[-1.4026749962821,53.730477294164],[-1.4028275726689,53.730841177609],[-1.4029349052792,53.731080906202],[-1.4030535254464,53.731324295156],[-1.4031981526337,53.731605554894],[-1.4033215836981,53.731830541691],[-1.4034607710418,53.732069062081],[-1.4036824508205,53.732424443727],[-1.4040828240196,53.733011359386],[-1.4046457607914,53.733740698984],[-1.4049583957794,53.734103756242],[-1.405467824829,53.734648945718],[-1.4061381456159,53.735294761825],[-1.4067269892232,53.735804826734],[-1.4072623707096,53.736234593532],[-1.4080288031469,53.736793670437],[-1.4087419934122,53.737261231708],[-1.4093044586493,53.737598050044],[-1.4281300027501,53.748312515645],[-1.4414538575684,53.755866489083],[-1.4437677428661,53.757159042336],[-1.4450130345638,53.757807166936],[-1.4460954515116,53.758330463036],[-1.447313561033,53.758886947651],[-1.4484514027606,53.759377419286],[-1.4499321409622,53.759981139725],[-1.4523655963268,53.760910098934],[-1.4534892465411,53.761303592439],[-1.4547408734582,53.761716523292],[-1.4571737507181,53.762467398629],[-1.4586285275453,53.762891517277],[-1.4599969310394,53.763258640096],[-1.4610664222771,53.763520609636],[-1.4628491062867,53.763901946143],[-1.4643955896749,53.764183763616],[-1.466074384806,53.764434898428],[-1.4671854244081,53.764583675887],[-1.4686272842393,53.764745611586],[-1.4700734587911,53.764872953703],[-1.4713368712018,53.764950901175],[-1.4730517536636,53.765016411604],[-1.4746054040783,53.765042560438],[-1.475793131315,53.765026643966],[-1.4785978093488,53.764914796503],[-1.4813294685641,53.764712264133],[-1.4827380501829,53.764645120589],[-1.4838175817499,53.764628307476],[-1.4847276879054,53.764633128362],[-1.4857970384654,53.764657374312],[-1.4869395584243,53.764716186401],[-1.4886059352048,53.764853351484],[-1.4898164358207,53.764997741104],[-1.4909738841884,53.765173127043],[-1.4924524940514,53.765450518996],[-1.5088725330397,53.768934764564],[-1.5109421415631,53.769402871347],[-1.5126951672919,53.769840247608],[-1.5146933787361,53.770372282192],[-1.5160480724259,53.770756072862],[-1.5168459749212,53.770997905014],[-1.5190954288769,53.771711717928],[-1.5206893547699,53.772255521847],[-1.5310840839517,53.775974624925],[-1.5322063304961,53.776423017151],[-1.5332638691866,53.776919134414],[-1.5342787058401,53.777484788017],[-1.5344955204229,53.777615048766],[-1.5348954078229,53.777867088348],[-1.5353145815524,53.778152618938],[-1.5360020832063,53.778665254103],[-1.5364684385215,53.779047045547],[-1.5369242157676,53.779458652682],[-1.5376410639531,53.780194888878],[-1.5379694100789,53.780578362453],[-1.5383637325365,53.781095921305],[-1.5392499617622,53.782493961337],[-1.539646817849,53.782942524099],[-1.5399819356885,53.783232164532],[-1.540351784256,53.783496626677],[-1.5406482624139,53.783677235771],[-1.541053062779,53.783885429432],[-1.5414544039211,53.784061853668],[-1.5421156544811,53.784298194446],[-1.5424103226828,53.784386862334],[-1.5428546350385,53.784499531621],[-1.5432329203362,53.784575285612],[-1.5436975800525,53.784641228392],[-1.5441291093017,53.784683377931],[-1.5462389989163,53.784834240991],[-1.5467796398615,53.784904719476],[-1.5473064699397,53.784993667802],[-1.5508401255287,53.785737065841],[-1.5513801537101,53.785861126013],[-1.551655646488,53.785927579804],[-1.5520599891262,53.786039049873],[-1.5523184161638,53.78611769813],[-1.5525601242148,53.786195798128],[-1.5527405539546,53.786258838942],[-1.5528311296866,53.786292126744],[-1.5532796257632,53.786465559089],[-1.5536823634278,53.786643376489],[-1.5540683175131,53.786844130581],[-1.55454445587,53.787121517842],[-1.5556016945465,53.787831386745],[-1.5559412853382,53.788115399091],[-1.5564363661941,53.788605542059],[-1.5567412939879,53.789006906736],[-1.5568944596416,53.78928384597],[-1.5573599358365,53.790277520911],[-1.5574695784831,53.790469092093],[-1.5575868855991,53.790659415123],[-1.5576438841213,53.790741668151],[-1.5578235651457,53.790957953638],[-1.5579301635756,53.791064009873],[-1.5580463785491,53.791166470259],[-1.5581718338436,53.791265027789],[-1.5583229726011,53.791360776586],[-1.5585495087426,53.791504277447],[-1.5588667369153,53.791665889667],[-1.5593130575441,53.791856296533],[-1.559580862162,53.791950126248],[-1.5600862040847,53.792101720741],[-1.5604828034387,53.792216782913],[-1.561004048561,53.792381140862],[-1.561261304167,53.792459540682]],[[-1.5614452815921,53.792516631152],[-1.5624317908212,53.792841042684],[-1.5634950704334,53.793246968242],[-1.5653369371176,53.793982260488],[-1.5672645066253,53.794811596534],[-1.5706510945746,53.796167696975],[-1.5719188430458,53.796671106795],[-1.5742873293066,53.797611483256],[-1.5761928875959,53.798352433072],[-1.579209414559,53.799557979185],[-1.5831605582087,53.801191185072],[-1.585868236959,53.802342082565],[-1.5881735432423,53.8032599532],[-1.5888440278234,53.803507049661],[-1.5900573379651,53.803926455419],[-1.5910536427237,53.8042976529],[-1.5915026223267,53.804483786721],[-1.592674328273,53.805024721934],[-1.594035814506,53.805656563265],[-1.5968748568668,53.80680209117],[-1.5979945956674,53.807287424322],[-1.5990621931341,53.80781470855],[-1.6003379079087,53.808543090898],[-1.6011302502227,53.809052353463],[-1.6020085548288,53.809703852304],[-1.6029811655596,53.810528819406],[-1.604067337001,53.811479364915],[-1.6047105371846,53.812117880094],[-1.6053779372412,53.812900144418],[-1.6067720131961,53.814737515485],[-1.6077652906994,53.816057443228],[-1.6083437865077,53.816932874914],[-1.6089828315153,53.817852730784],[-1.6094387997672,53.818409313296],[-1.6098185356524,53.818814639087],[-1.6104319784414,53.819389507684],[-1.6110054277775,53.819849511851],[-1.6115326285733,53.820226530313],[-1.6122079995487,53.820654915119],[-1.6126757368589,53.82092308964],[-1.6136039178397,53.821393887288],[-1.6143249526521,53.821712259301],[-1.6151539429271,53.822032249372],[-1.6159896455499,53.822312267631],[-1.6167253177747,53.822523454343],[-1.6175321359518,53.822716285062],[-1.6184738802934,53.82289478995],[-1.6211424522619,53.823285140338],[-1.6221467070369,53.823490507877],[-1.6227208492013,53.823631537323],[-1.6234610407053,53.823838050018],[-1.6241465403133,53.824057626199],[-1.6249889719669,53.824369357101],[-1.6260218945173,53.824813439279],[-1.6280328959902,53.825738266517],[-1.6286109930341,53.825980691164],[-1.6294174127383,53.826277170582],[-1.6301293746741,53.826499885926],[-1.630734771874,53.826663658767],[-1.6313688018327,53.826812920002],[-1.6320669459468,53.826950267587],[-1.6326698074361,53.827047700652],[-1.6333411424956,53.827133107199],[-1.6346433251542,53.82723491102],[-1.6356667455695,53.827251053628],[-1.6363125235981,53.827232590923],[-1.6370408668086,53.827183060309],[-1.6375767834019,53.827128001168],[-1.638377170257,53.82701437101],[-1.6407845818016,53.826580747376],[-1.6415153928964,53.826483947265],[-1.6425057512555,53.826398674419],[-1.6434342949182,53.8263628234],[-1.6445806277094,53.826372271321],[-1.6456910796435,53.826440887016],[-1.6463177336492,53.826508499621],[-1.6469805686126,53.826604293737],[-1.6474719734021,53.82669150077],[-1.6484769300599,53.826912441396],[-1.6492064017033,53.827105677012],[-1.6520474452444,53.827910376402],[-1.653496597106,53.828319600767],[-1.6542623343935,53.828518572602],[-1.6549566991729,53.828671675619],[-1.6559001627755,53.82884279058],[-1.6566025381454,53.828948468568],[-1.6578704726372,53.8290811463],[-1.6605418823796,53.829292755287],[-1.6612352590941,53.829363642232],[-1.6620602078529,53.829474649279],[-1.6626917187798,53.829580146029],[-1.6635455859374,53.829750292917],[-1.6644597807585,53.82996573083],[-1.6655274634843,53.830267828821],[-1.6667870521449,53.830691257048],[-1.6672645144343,53.830875324134],[-1.6681681428816,53.831262563013],[-1.6714226574045,53.832805243444],[-1.672449924748,53.833264997269],[-1.6744538305327,53.834148011819],[-1.6805810271329,53.837056534394],[-1.6813870297865,53.837420116541],[-1.6823986211466,53.837837958044],[-1.6834733267691,53.838225721922],[-1.6838432928821,53.838347584244],[-1.6838828122982,53.838360567993],[-1.6843442916422,53.838504995658],[-1.6844436646546,53.838534925997],[-1.6848927139519,53.838665585317],[-1.6852014549591,53.838751744472],[-1.6863207575344,53.839034890196],[-1.6877291109807,53.839312863356],[-1.6889461323637,53.839491169653],[-1.6915005089969,53.839812102618],[-1.7037021613302,53.841558145427],[-1.7047763024579,53.841723858582],[-1.7074161895882,53.842200387246],[-1.7086986952383,53.842398839304],[-1.7160534897109,53.843464399227],[-1.720307964937,53.844189370844],[-1.7350742182143,53.846289564452],[-1.7363833065116,53.846419803265],[-1.7376179979804,53.846475238681],[-1.7389763047932,53.846467798992],[-1.7398079068304,53.846426164634],[-1.7405064872449,53.846369029682],[-1.7416218446532,53.84623301118],[-1.7428656093321,53.846018145674],[-1.7438049180264,53.845784148167],[-1.7448900258208,53.845446660653],[-1.7454944030749,53.845225123402],[-1.7461477174567,53.844960283912],[-1.7470778256006,53.844540955555],[-1.7497361283444,53.843240399994],[-1.7510594534923,53.84268574637],[-1.7530890190282,53.841918358905],[-1.765139838005,53.837101085131],[-1.7669849218719,53.836343644382],[-1.7677775306681,53.836018800969],[-1.7682226880473,53.835836361098],[-1.768603434815,53.83568030089],[-1.768859232392,53.835575769527],[-1.7690285634478,53.835505072693],[-1.7698693695051,53.835141525231],[-1.7710740368221,53.83460810208],[-1.7716033649936,53.834416408666],[-1.7719843468072,53.834307551714],[-1.772473676358,53.834208066507],[-1.7727630956624,53.834165562213],[-1.7734246168333,53.834109873321],[-1.7740025789884,53.834113667453],[-1.7742568067167,53.834127384695],[-1.7749017219865,53.834195653818],[-1.7757117754777,53.834332697904],[-1.7761955430147,53.834434327821],[-1.7771947729154,53.834693761158],[-1.7781529841568,53.834945317879],[-1.7784943626775,53.835031099396],[-1.7786820642271,53.835081067662],[-1.7789792650123,53.835162461182],[-1.7804397628767,53.83560629346],[-1.786534755492,53.837564573381],[-1.7876490845623,53.837880819622],[-1.7884133006282,53.83807147143],[-1.7892804366301,53.838264518938],[-1.7903653793119,53.838472132335],[-1.7914867560857,53.838640468044],[-1.792014506774,53.838703660078],[-1.7930315089827,53.838789075864],[-1.7941033044941,53.838839254451],[-1.7952118344425,53.838845418356],[-1.8094964000036,53.838484467793],[-1.8108457931619,53.838478959934],[-1.8123783272591,53.83851909397],[-1.8141274367042,53.838626251898],[-1.8156303044555,53.838769407774],[-1.8167314077537,53.838907196095],[-1.8179834212886,53.839097548559],[-1.8195016521341,53.839378796337],[-1.8210455175241,53.839722528998],[-1.8224949768886,53.840101541651],[-1.8243003932565,53.840666433228],[-1.8256042278085,53.841130831954],[-1.8261240787045,53.841330802091],[-1.8272407571089,53.841793348125],[-1.82793483019,53.842102242407],[-1.8291199092403,53.842691894767],[-1.8298476092749,53.843110810647],[-1.8302433891005,53.843361521538],[-1.830811060096,53.843749718417],[-1.8314510382691,53.84422950181],[-1.8371840558829,53.848714292383],[-1.8380916625793,53.849446548312],[-1.8387078150616,53.850051479587],[-1.8391283675175,53.850568550064],[-1.8395083781518,53.851176090874],[-1.8397288009518,53.851628412678],[-1.8407429878913,53.854068856308],[-1.8411518813153,53.854848188168],[-1.8415049949439,53.855398128258],[-1.8418451066965,53.855862602391],[-1.8423274578977,53.856430065506],[-1.8426373482994,53.85675647983],[-1.8431694198852,53.857258788511],[-1.8434992472509,53.85754226452],[-1.8440532325961,53.857978923331],[-1.844556557598,53.858341094456],[-1.8452421314809,53.858787795452],[-1.8461703376052,53.859331926143],[-1.8469512092521,53.859734033508],[-1.8478860602973,53.860159708128],[-1.8485651283916,53.860434183131],[-1.8491071680105,53.860632265237],[-1.8498580989063,53.860888146271],[-1.8507791598509,53.861166523777],[-1.8516185278406,53.861383163589],[-1.8524690092536,53.861576658408],[-1.8533956511484,53.861755176409],[-1.8542057026807,53.861887465135],[-1.8547736694593,53.861965942475],[-1.8576015039259,53.862292222785],[-1.8594641359979,53.862556769977],[-1.8616994724082,53.862969082502],[-1.8628215795778,53.863229487935],[-1.8641093763746,53.863584955082],[-1.8718862002734,53.865853264079],[-1.8801740364712,53.86825964946],[-1.8808992201205,53.868432415154],[-1.8819576089482,53.86863001376],[-1.8828158203901,53.868744666013],[-1.8837692204904,53.868826104132],[-1.8850230062657,53.86886148975],[-1.8856638206499,53.868849068087],[-1.8864565898789,53.868807540035],[-1.8874953379815,53.868703259129],[-1.8885194292267,53.868544291527],[-1.8892366876717,53.868398101445],[-1.8897564520404,53.868272416316],[-1.892305824671,53.867535168587],[-1.8931874100898,53.867316668729],[-1.8940135228909,53.867172218409],[-1.8945834580119,53.867106083112],[-1.8950375856862,53.867072820588],[-1.8959721875331,53.867051189526],[-1.8971762638739,53.867087034387],[-1.8982489829146,53.867174364436],[-1.8987024724214,53.867234642088],[-1.8992152486982,53.86732283903],[-1.9002520785858,53.867562258517],[-1.901181691146,53.867855238531],[-1.9021001532435,53.868233703703],[-1.9027592229916,53.868560452125],[-1.9033263205582,53.868864150119],[-1.9037915341216,53.869135344837],[-1.9043556346675,53.869493025557],[-1.904929653882,53.869914075781],[-1.9052606940023,53.87020587569],[-1.9054128184072,53.870354780194],[-1.9058783322686,53.870892447713],[-1.9062235379685,53.871419485949],[-1.9064804955644,53.871981399362],[-1.9066382449125,53.87260184501],[-1.9066764551112,53.872859610108],[-1.9068416660272,53.873979749374],[-1.9069638688086,53.874469420713],[-1.9072199264212,53.875073026151],[-1.9074053762353,53.875391518305],[-1.9077127975942,53.875813751508],[-1.9082532426795,53.876417787986],[-1.9102867223172,53.878512758851],[-1.9120128033376,53.880290873775],[-1.9126896769397,53.880962766652],[-1.9133475616403,53.881536548767],[-1.9136720393802,53.881793321519],[-1.9145593231378,53.882418995101],[-1.9153881971027,53.882926107501],[-1.9161382647028,53.88333112944],[-1.9164659736859,53.883493228001],[-1.9172156898107,53.88383996584],[-1.9179213925721,53.884131834248],[-1.9194592865727,53.884719858506],[-1.9226411866224,53.88591821469],[-1.9238386684981,53.886395593063],[-1.9247845609263,53.886817967927],[-1.9257068494173,53.887272236508],[-1.9263190955402,53.887602303781],[-1.9269480246374,53.887968320325],[-1.9278072820191,53.888502588956],[-1.9282972732984,53.888820070696],[-1.929389686655,53.889572349139],[-1.9307508883915,53.890600176989],[-1.9315005764734,53.891217466253],[-1.933115726449,53.892611457761],[-1.9347956142572,53.894050868647],[-1.9376133238499,53.896475149655],[-1.9380976626441,53.896859349441],[-1.9386246952756,53.897244090276],[-1.9396089083106,53.897875872733],[-1.9399215901964,53.898058148818],[-1.9404708882052,53.898356996102],[-1.9412012791921,53.898718870875],[-1.9418762176406,53.899021385975],[-1.9425465939787,53.899295089181],[-1.9437033150203,53.899708408416],[-1.9445625704762,53.899976813619],[-1.9451457272211,53.900135993505],[-1.9460155729186,53.900348893426],[-1.9465940948393,53.900475051996],[-1.947455783566,53.900638208353],[-1.9482010316666,53.900757232424],[-1.9491107545835,53.900877687471],[-1.9497958438891,53.900951251912],[-1.9877057655419,53.904022287903],[-1.9888346621853,53.904140989667],[-1.9898782046081,53.904282116361],[-1.9906419019508,53.904403457939],[-1.9921251329051,53.904686532846],[-1.993642695766,53.905041493515],[-1.9951951766414,53.905477272519],[-1.9964008853527,53.905871256014],[-1.997550282035,53.906298912607],[-1.9987498844942,53.906808311537],[-1.9995760901813,53.907193756891],[-2.0003223829261,53.9075706226],[-2.0012026277925,53.908051273076],[-2.0016810881435,53.908334219853],[-2.0024334551518,53.908821532186],[-2.003906801083,53.909882776958],[-2.0076883687623,53.912644846789],[-2.0088207761591,53.913578722798],[-2.0094813084364,53.914200310845],[-2.0101167735793,53.914893772631],[-2.0104227485631,53.915251782941],[-2.0109236014469,53.915895486916],[-2.0122226758808,53.917774505093],[-2.0131030290522,53.919067571196],[-2.0164097648061,53.923908590167],[-2.0201690435765,53.929567908221],[-2.0209401751053,53.930893198924],[-2.021251106643,53.931537790315],[-2.0215803489548,53.932287938662],[-2.0219020715119,53.933196244863],[-2.022214847103,53.934378606207],[-2.0224301900535,53.935536385484],[-2.0225320683541,53.936670691768],[-2.022537924924,53.937634311781],[-2.0225130750689,53.938127177431],[-2.0224229283466,53.938997378806],[-2.022271863077,53.939844735604],[-2.0219443772517,53.941390292442],[-2.0217127565989,53.94268319419],[-2.0199145658384,53.951050745454],[-2.0198067751039,53.951935245404],[-2.0197780585773,53.953029190815],[-2.0198282837919,53.953886476176],[-2.0199003216351,53.954436260901],[-2.020037785796,53.954932503644],[-2.020239046435,53.955373002481],[-2.0204023771437,53.955650955621],[-2.0206830045219,53.956048937072],[-2.0210881275976,53.95647803822],[-2.0214488609201,53.956779107002],[-2.0218555809117,53.957058676603],[-2.0221630742116,53.957239901822],[-2.022570389489,53.957448447949],[-2.0233352931806,53.95776403857],[-2.0237352197162,53.957904913682],[-2.0243768554983,53.958101372085],[-2.024774266479,53.958203947599],[-2.0251864369025,53.95829005318],[-2.025772885222,53.958387336375],[-2.0263638909491,53.958457418876],[-2.0267425479804,53.958486598362],[-2.0273344578532,53.958513480935],[-2.0279062228311,53.958520250814],[-2.0289526591037,53.958490296536],[-2.0300318755592,53.958376811049],[-2.0369365621736,53.956747663922],[-2.0383501495219,53.95641407925],[-2.0386581036447,53.956363855391]]]}

**Comment by adoroszlai** [comment]
I have no problem displaying your MultiLineString with markers.  Do you have a live example?

**Comment by adoroszlai** [comment]
@matbeard were you able to resolve the problem?
