### ISSUE TITLE
Conflict with marker clusters

### ISSUE THREAD

**Issue by arminus** [adoroszlai/leaflet-distance-markers#7]
When using this plugin along with Leaflet.markercluster I get the following effect:

![2017-01-13_144344](https://cloud.githubusercontent.com/assets/683680/21932033/cdb376f2-d99e-11e6-9cc6-d36b926baad4.png)

Is there any way to avoid the distance points on the marker cluster lines?

**Comment by adoroszlai** [comment]
@arminus 

To hide the distance markers for cluster lines, create the cluster like this:

```
L.markerClusterGroup({
  spiderLegPolylineOptions: {
    weight: 1.5, color: '#222', opacity: 0.5, // for defaults
    distanceMarkers: { lazy: true }, // for hiding the markers
  }
})
```

Now the `lazy` flag means some of the distance marker data is still created, but hidden.  If you prefer to avoid that, too, I'm adding a new flag `disabled` on branch no-markers.

https://github.com/adoroszlai/leaflet-distance-markers/compare/no-markers

Please let me know if that's works for you.

**Comment by arminus** [comment]
@adoroszlai 

Thanks for the quick response, the lazy option works fine for me.

**Comment by adoroszlai** [comment]
Great, closing the issue then.
