### ISSUE TITLE
Change accumelated count

### ISSUE THREAD

**Issue by sydgis** [adoroszlai/leaflet-distance-markers#9]
Is it possible to change accumulated count of markers to 5 - 10 - 15 instead of 1 - 2 - 3 ? 
Thank you

**Comment by TheGreatRefrigerator** [comment]
@sydgis 
How about using the offset parameter ?
https://github.com/adoroszlai/leaflet-distance-markers#options

**Comment by adoroszlai** [comment]
Using `offset: 5000` would show markers at 5-10-15 km, but with labels 1-2-3.

**Comment by adoroszlai** [comment]
Thanks to @matzepan this is now possible with the following options:

```
distanceMarkers: {
	offset: 5000,
	textFunction: function(distance, i, offset) {
		return distance/1000;
	}
}
```
